# TODO: trigger only if testing or any other checks previously succeeded
name: Push to DockerHub (main)
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-multiarch:
    runs-on: ubuntu-latest-8-cores

    steps:
      - id: checkout
        uses: actions/checkout@v6.0.2 # v4
        with:
          persist-credentials: 'false'
      - id: push-beyla-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@issues-update-project-status/v0.1.0 # main
        with:
          repository: grafana/beyla
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "main"
          push: true

      - id: push-beyla-k8s-cache-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@issues-update-project-status/v0.1.0 # main
        with:
          repository: grafana/beyla-k8s-cache
          file: k8scache.Dockerfile
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "main"
          push: true
