name: Test Docker build
on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read

jobs:
  build-multiarch:
    runs-on: ubuntu-latest-8-cores

    steps:
      - id: checkout
        uses: actions/checkout@v6.0.2 # v4
        with:
          persist-credentials: 'false'
      - id: docker-build-beyla
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@issues-update-project-status/v0.1.0 # main
        with:
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "pr-test"
          push: false

      - id: docker-build-cache
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@issues-update-project-status/v0.1.0 # main
        with:
          repository: grafana/beyla-k8s-cache
          file: k8scache.Dockerfile
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "pr-test"
          push: false
